_wandb:
    value:
        cli_version: 0.27.0
        e:
            x3prm4ewt9slr301ttqwmi5qvyktfbnd:
                codePath: vanilla_sweep_train.py
                codePathLocal: vanilla_sweep_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "838859747328"
                        used: "79256383488"
                email: 124111030@nitkkr.ac.in
                executable: D:\Desktop\Programming\ML\dl_env\Scripts\python.exe
                git:
                    commit: 1e72982ad2ab09f5fbe0f0dd8d04d458351fef75
                    remote: https://github.com/BVedhashreyan/Seq2Seq-ScriptMapper
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-27bafa62-4995-ee2f-a77c-e59e31ac4576
                host: Vedh-Laptop
                memory:
                    total: "16356962304"
                os: Windows-11-10.0.26200-SP0
                program: D:\Desktop\Programming\ML\transliteration_seq2seq\vanilla_sweep_train.py
                python: CPython 3.14.5
                root: D:\Desktop\Programming\ML\transliteration_seq2seq
                startedAt: "2026-06-27T11:11:50.334155Z"
                writerId: x3prm4ewt9slr301ttqwmi5qvyktfbnd
        m: []
        python_version: 3.14.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.14.5
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
cell_type:
    value: LSTM
dropout:
    value: 0.1
embedding_dim:
    value: 64
epochs:
    value: 5
hidden_dim:
    value: 512
num_layers:
    value: 2
